---
- name: Setup Redhat
  ansible.builtin.include_tasks: "setup-docker.yml"

- name: Ensure config file is present
  ansible.builtin.file:
    path: "/etc/docker"
    mode: '0755'
    state: directory

- name: Copy daemon.json file
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker
  notify: Restart docker

- name: Install Docker
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present
  notify: Restart docker
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure Docker is started and enabled at boot
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install docker
  ansible.builtin.include_tasks: "docker-compose.yml"
  when: docker_install_compose | bool
