---
- name: Setup Redhat
  ansible.builtin.include_tasks: "setup-docker.yml"

- name: Ensure config file is present
  ansible.builtin.file:
    path: "/etc/docker"
    mode: '0755'
    state: directory

- name: Copy daemon.json file
  ansible.builtin.copy:
    src: files/daemon.json
    dest: /etc/docker
  notify: Restart docker

- name: Install Docker
  ansible.builtin.package:
    name: "{{ docker_packages }}"
    state: present
    enablerepo: "docker-ce-stable_el_8"
  notify: Restart docker
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure Docker is started and enabled at boot
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install docker
  ansible.builtin.include_tasks: "docker-compose.yml"
  when: docker_install_compose | bool

  # - name: Log into private registry
  #  community.docker.docker_login:
  #    registry_url: ""
  #    username: stacks_reader
  #    password:

- name: Yum version Lock
  community.general.yum_versionlock:
    state: present
    name:
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - containerd.io
