---
name: Deploy on Pull Request

on:
  pull-request:
    types:
      - opened

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Deploy Docker Compose
        run: |
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
          docker-compose -f /home/morgott/product/Heinrich-Von-Zimmel/docker-compose.yml up -d

