---
name: Manual deployment wordpress

# Configure Manual Trigger
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    environment:
      MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
      MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
    steps:
      - name: deploy application
        run: |
          docker-compose -f /home/morgott/product/Heinrich-Von-Zimmel/docker-compose.yml up -d
