---
name: Deploy on Pull Request

on:
  pull_request:
    types: [opened]

jobs:
  deploy:
    runs-on: self-hosted

    if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.event.pull_request.merged == true

    steps:
      - name: Deploy Docker Compose
        run: |
          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
          docker-compose -f /home/morgott/product/Heinrich-Von-Zimmel/docker-compose.yml up -d

