---
name: Deploy on Pull Request

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Pull latest changes from GitHub
        run: hostname 
            #      - name: Deploy Docker Compose
            #        run: |
            #          MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} \
            #          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} \
            #          docker-compose -f /path/to/your/docker-compose.yml up -d

